services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      redis:
       condition: service_started
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
